### GET request to example server
GET http://localhost:8888/api/shopping-items/1
Accept: application/json

###

### GET request to example server
GET http://localhost:8888/api/shopping-items/100000
Accept: application/json

###