### GET request to example server
POST {{url}}/api/shopping-items
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token}}

{
  "name": "New Item",
  "note": "test note",
  "quantity": 1
}

### GET request to example server
POST {{url}}/api/shopping-items
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token}}

{
  "name": "",
  "note": "",
  "quantity": -3
}

###