### GET request to example server
GET {{url}}/api/shopping-items/1
Accept: application/json
Authorization: Bearer {{auth_token}}

###

### GET request to example server
GET {{ url }}/api/shopping-items/100000
Accept: application/json
Authorization: Bearer {{auth_token}}

###